### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by JustFrederik** [JustFrederik/cargo-dependency-language-server#1]
- [ ] inlay hints to indicate newer versions
- [ ] warn if newer version is available
- [ ] code action update
- [ ] code action open docs.rs
- [ ] code action convert dependency simple <=> advanced
- [ ] completion for versions
- [ ] completion for features
